### ISSUE TITLE
Add UTF-8 meta-tag to academix

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/academix-frontend#36]
**Is your feature request related to a problem?**
Symbols are not working properly. Such as copyright symbol in footer is showing with some other character.

**Describe the solution you'd like**
Add UTF-8 meta tag to index.html

**Screenshots**
![Screenshot from 2020-06-27 14-08-20](https://user-images.githubusercontent.com/60275681/85918360-ba0d1b80-b87f-11ea-906f-7c77ccab7bf6.png)

**Comment by jayasanka-sack** [comment]
The issue is still there
