### ISSUE TITLE
Outdated year in the footer

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/academix-frontend#65]
**Is your feature request related to a problem?**
- The footer on the Academix page is outdated.

**Describe the solution you'd like**
- Update the year `2020` with `2021`

**Comment by gajindubandara** [comment]
Can you assign this to me?

**Comment by Gimhan-minion** [comment]
@gajindubandara Sure go ahead!

**Comment by Gravewalker666** [comment]
Yeah sure @gajindubandara, rather than putting a static text use js to get the current year
