### ISSUE TITLE
Incorrect URL linked the the navbar

### ISSUE THREAD

**Issue by Gimhan-minion** [sef-global/academix-frontend#66]
**Is your feature request related to a problem?**
- In the navbar, item `blog` redirects to an old URL

**Describe the solution you'd like**
- Replace the old URL with the new SEF medium URL `https://sefglobal.medium.com/`

**Comment by gajindubandara** [comment]
Can you assign this to me?

**Comment by Gimhan-minion** [comment]
Yeah sure go ahead :)  @gajindubandara
