### ISSUE TITLE
The footer year should be changed in the academix 

### ISSUE THREAD

**Issue by VishwaAmarasinghe** [sef-global/academix-frontend#69]
**Is your feature request related to a problem? Please describe.**
The footer year in the academix is a wrong .

**Describe the solution you'd like**
The footer year should be 2022

**Describe alternatives you've considered**
Make the footer to 2022

**Additional context**
N/A

**Are you working on it?**
Yes

**Comment by Piumal1999** [comment]
Oh this is already fixed with #68. But it is not deployed. The latest version will be deployed with #70 

So, I'm closing this issue
