### ISSUE TITLE
Update the API_URL variable

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/academix-frontend#87]
**Is your feature request related to a problem? Please describe.**
Now the backend of the academic is deployed at core.sefglobal.org. So we need to update the API_URL of academix frontend.

**Describe the solution you'd like**
Update the API_URL
Related file: https://github.com/sef-global/academix-frontend/blob/master/src/contants.ts
The new API_URL is https://core.sefglobal.org

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on this issue?**
No

**Comment by ridmajayasundara** [comment]
I would like to assign this to myself.

**Comment by Piumal1999** [comment]
Sure, assigned @ridmajayasundara
